FROM harbor.dankal.cn/common/springboot

ENV VIRTUAL_PORT 8080
ENV VIRTUAL_HOST api-bsd.dankal.cn
ENV LETSENCRYPT_HOST api-bsd.dankal.cn
ENV LETSENCRYPT_EMAIL bingo@dankal.cn

COPY ./web/target/javaee_bsd.jar /app/app.jar